const SUPABASE_URL="https://pophcxrfrooqluwrujbl.supabase.co",SUPABASE_KEY="sb_publishable_cmZlKwLESb-jIWkkQAC7yg_KxNdkJfn",db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=i=>document.getElementById(i),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function showMsg(t,type="ok"){const m=$("msg");m.textContent=t;m.className="msg "+type;m.style.display="block";setTimeout(()=>m.style.display="none",4000)}
async function requireLogin(){const{data:{user}}=await db.auth.getUser();if(!user){location.href="login.html";return null}$("adminEmail").textContent=user.email||"مدیر";return user}async function logout(){await db.auth.signOut();location.href="login.html"}
async function uploadFile(f,b){if(!f)return null;const p=Date.now()+"_"+Math.random().toString(36).slice(2,8)+"_"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_");const{error}=await db.storage.from(b).upload(p,f,{cacheControl:"3600",upsert:false});if(error)throw error;return db.storage.from(b).getPublicUrl(p).data.publicUrl}
async function loadAdminBooks(){const l=$("booksList"),{data,error}=await db.from("books").select("*").order("created_at",{ascending:false});if(error){l.textContent="خطا در دریافت کتاب‌ها.";return}if(!data?.length){l.textContent="هنوز کتابی اضافه نشده است.";return}l.innerHTML=data.map(b=>`<div class="book-row">${b.cover_url?`<img class="thumb" src="${esc(b.cover_url)}" alt="">`:`<div class="thumb">بدون تصویر</div>`}<div><h3>${esc(b.title)}</h3><p>نویسنده: ${esc(b.author||"نامشخص")}</p><p>دسته: ${esc(b.category||"بدون دسته")}</p><p>امتیاز: ${b.rating!=null?esc(b.rating):"-"}</p></div><div class="row-actions"><button class="primary" onclick="startEdit('${b.id}')">ویرایش</button><button class="danger" onclick="deleteBook('${b.id}')">حذف</button></div></div>`).join("")}
async function startEdit(id){const{data:b,error}=await db.from("books").select("*").eq("id",id).single();if(error||!b){showMsg("کتاب پیدا نشد.","error");return}$("bookId").value=b.id;$("title").value=b.title||"";$("author").value=b.author||"";$("category").value=b.category||"";$("rating").value=b.rating??"";$("description").value=b.description||"";$("formTitle").textContent="ویرایش کتاب";$("saveBtn").textContent="ذخیره تغییرات";$("cancelEdit").style.display="inline-block";scrollTo({top:0,behavior:"smooth"})}function resetForm(){$("bookForm").reset();$("bookId").value="";$("formTitle").textContent="افزودن کتاب";$("saveBtn").textContent="ذخیره کتاب";$("cancelEdit").style.display="none"}
async function saveBook(e){e.preventDefault();const id=$("bookId").value.trim(),title=$("title").value.trim();if(!title){showMsg("عنوان کتاب را وارد کنید.","error");return}const btn=$("saveBtn");btn.disabled=true;try{let cu=null,pu=null;if($("cover").files[0])cu=await uploadFile($("cover").files[0],"covers");if($("pdf").files[0])pu=await uploadFile($("pdf").files[0],"books");const p={title,author:$("author").value.trim(),category:$("category").value.trim(),description:$("description").value.trim(),rating:$("rating").value.trim()===""?null:Number($("rating").value)};if(cu)p.cover_url=cu;if(pu)p.pdf_url=pu;const r=id?await db.from("books").update(p).eq("id",id):await db.from("books").insert(p);if(r.error)throw r.error;showMsg(id?"کتاب ویرایش شد.":"کتاب اضافه شد.");resetForm();await loadAdminBooks()}catch(e){showMsg(e.message||"خطا","error")}finally{btn.disabled=false}}
async function deleteBook(id){if(!confirm("آیا از حذف این کتاب مطمئن هستید؟"))return;const{error}=await db.from("books").delete().eq("id",id);if(error){showMsg(error.message,"error");return}showMsg("کتاب حذف شد.");await loadAdminBooks();await loadViewStats();await loadWeeklyViews()}
async function loadViewStats(){const{count,error:te}=await db.from("page_views").select("*",{count:"exact",head:true});if(!te)$("totalViews").textContent=count||0;const s=new Date();s.setHours(0,0,0,0);const{data,error}=await db.from("page_views").select("book_id,page,created_at").gte("created_at",s.toISOString());if(error)return;const t=data||[];$("todayViews").textContent=t.length;$("homeViews").textContent=t.filter(v=>v.page==="home").length;$("bookViews").textContent=t.filter(v=>v.page==="book").length;const c={};t.filter(v=>v.page==="book"&&v.book_id).forEach(v=>c[v.book_id]=(c[v.book_id]||0)+1);const ids=Object.keys(c),el=$("popularViews");if(!ids.length){el.innerHTML='<div class="chart-empty">امروز هنوز بازدیدی برای کتاب‌ها ثبت نشده است.</div>';return}const{data:bs}=await db.from("books").select("id,title").in("id",ids);const m={};(bs||[]).forEach(b=>m[b.id]=b);el.innerHTML=ids.sort((a,b)=>c[b]-c[a]).slice(0,10).map((id,i)=>m[id]?`<div class="view-row"><strong>${i+1}</strong><span>${esc(m[id].title)}</span><b>${c[id]} بازدید</b></div>`:"").join("")}
async function loadWeeklyViews(){const ch=$("viewsChart");if(!ch)return;const s=new Date();s.setHours(0,0,0,0);s.setDate(s.getDate()-6);const{data,error}=await db.from("page_views").select("created_at").gte("created_at",s.toISOString());if(error){ch.innerHTML='<div class="chart-empty">خطا در دریافت نمودار</div>';return}const d=[];for(let i=0;i<7;i++){const x=new Date(s);x.setDate(s.getDate()+i);d.push({date:x,count:0})}(data||[]).forEach(v=>{const x=new Date(v.created_at);x.setHours(0,0,0,0);const q=d.find(z=>z.date.getTime()===x.getTime());if(q)q.count++});const max=Math.max(...d.map(x=>x.count),1);ch.innerHTML=d.map(x=>`<div class="chart-row"><span>${x.date.toLocaleDateString("fa-IR",{month:"numeric",day:"numeric"})}</span><div><div class="chart-bar" style="width:${Math.max(3,x.count/max*100)}%"></div></div><b>${x.count}</b></div>`).join("")}
function toISO(v){return v?new Date(v).toISOString():null}function fromISO(v){if(!v)return"";const d=new Date(v);const p=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
async function loadAds(){const{data,error}=await db.from("ads").select("*").order("created_at",{ascending:false});const el=$("adsList");if(error){el.textContent="برای مدیریت تبلیغات ابتدا ads.sql را اجرا کنید.";return}if(!data?.length){el.textContent="هنوز تبلیغی ثبت نشده است.";return}el.innerHTML=data.map(a=>`<div class="ad-item"><strong>${esc(a.title)}</strong><div class="muted">وضعیت: ${a.active?"فعال":"غیرفعال"}</div><div class="muted">زمان: ${a.start_at?fromISO(a.start_at):"بدون شروع"} تا ${a.end_at?fromISO(a.end_at):"بدون پایان"}</div><div class="row-actions" style="margin-top:8px"><button class="primary" onclick="editAd('${a.id}')">ویرایش</button><button class="danger" onclick="deleteAd('${a.id}')">حذف</button></div></div>`).join("")}
async function editAd(id){const{data:a,error}=await db.from("ads").select("*").eq("id",id).single();if(error||!a){showMsg("تبلیغ پیدا نشد.","error");return}$("adId").value=a.id;$("adTitle").value=a.title||"";$("adContent").value=a.content||"";$("adImage").value=a.image_url||"";$("adLink").value=a.link_url||"";$("adStart").value=fromISO(a.start_at);$("adEnd").value=fromISO(a.end_at);$("adActive").value=String(a.active);$("adSave").textContent="ذخیره تغییرات";$("adCancel").style.display="inline-block";scrollTo({top:0,behavior:"smooth"})}
function resetAdForm(){$("adForm").reset();$("adId").value="";$("adActive").value="true";$("adSave").textContent="ذخیره تبلیغ";$("adCancel").style.display="none"}
async function saveAd(e){e.preventDefault();const p={title:$("adTitle").value.trim(),content:$("adContent").value.trim(),image_url:$("adImage").value.trim()||null,link_url:$("adLink").value.trim()||null,active:$("adActive").value==="true",start_at:toISO($("adStart").value),end_at:toISO($("adEnd").value)};if(!p.title){showMsg("عنوان تبلیغ را وارد کنید.","error");return}const id=$("adId").value.trim();const r=id?await db.from("ads").update(p).eq("id",id):await db.from("ads").insert(p);if(r.error){showMsg(r.error.message,"error");return}showMsg(id?"تبلیغ ویرایش شد.":"تبلیغ اضافه شد.");resetAdForm();await loadAds()}
async function deleteAd(id){if(!confirm("آیا از حذف این تبلیغ مطمئن هستید؟"))return;const{error}=await db.from("ads").delete().eq("id",id);if(error){showMsg(error.message,"error");return}showMsg("تبلیغ حذف شد.");await loadAds()}
$("adForm")?.addEventListener("submit",saveAd);$("adCancel")?.addEventListener("click",resetAdForm);loadAds();
