const SUPABASE_URL="https://pophcxrfrooqluwrujbl.supabase.co",SUPABASE_KEY="sb_publishable_cmZlKwLESb-jIWkkQAC7yg_KxNdkJfn";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),grid=document.getElementById("booksGrid"),popular=document.getElementById("popularGrid"),best=document.getElementById("bestBooks");let books=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function card(b){const c=b.cover_url||"https://via.placeholder.com/300x450?text=Book";return `<article class="book-card"><a href="book.html?id=${encodeURIComponent(b.id)}"><img src="${esc(c)}" alt="${esc(b.title)}" loading="lazy"></a><div class="book-info"><h3>${esc(b.title)}</h3><p>${esc(b.author||"نامشخص")}</p><div class="rating">${b.rating!=null?"امتیاز "+esc(b.rating):"بدون امتیاز"}</div><a class="book-btn" href="book.html?id=${encodeURIComponent(b.id)}">مشاهده کتاب</a></div></article>`}
function render(a){grid.innerHTML=a.length?a.map(card).join(""):"<div class='loading'>کتابی پیدا نشد.</div>"}
async function recordHomeView(){try{await db.from("page_views").insert({page:"home"})}catch(e){}}
async function loadBooks(){const{data,error}=await db.from("books").select("*").order("created_at",{ascending:false});if(error){grid.innerHTML="<div class='loading'>خطا در دریافت کتاب‌ها.</div>";return}books=data||[];render(books);const s=[...books].sort((a,b)=>(Number(b.rating)||0)-(Number(a.rating)||0));if(popular)popular.innerHTML=s.slice(0,6).map(card).join("");if(best)best.innerHTML=s.slice(0,5).map((b,i)=>`<div class="best"><div>${i+1}</div><div class="best-info"><b>${esc(b.title)}</b><span>امتیاز ${esc(b.rating??"-")}</span></div><img src="${esc(b.cover_url||"https://via.placeholder.com/100x140")}" alt=""></div>`).join("")}
function goSearch(q){q=q.trim();if(q)location.href="search.html?q="+encodeURIComponent(q)}
document.getElementById("homeSearchForm")?.addEventListener("submit",e=>{e.preventDefault();goSearch(document.getElementById("searchInput").value)});
document.querySelectorAll("[data-category]").forEach(x=>x.addEventListener("click",()=>{const c=x.dataset.category;render(c==="همه"?books:books.filter(b=>(b.category||"").trim()===c));document.querySelectorAll("[data-category]").forEach(y=>y.classList.remove("active"));x.classList.add("active")}));
const dm=document.getElementById("darkMode");if(localStorage.getItem("darkMode")==="1")document.body.classList.add("dark");dm?.addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("darkMode",document.body.classList.contains("dark")?"1":"0")});document.getElementById("newsletterBtn")?.addEventListener("click",()=>alert("عضویت شما ثبت شد."));
function adHtml(a,close=false){const media=a.image_url?`<img src="${esc(a.image_url)}" alt="${esc(a.title)}">`:"";const body=`<div class="ad-label">تبلیغ</div><h3>${esc(a.title)}</h3>${media}<p>${esc(a.content||"")}</p>`;return a.link_url?`<a class="ad-link" href="${esc(a.link_url)}" target="_blank" rel="noopener">${body}</a>`:body}
async function loadAds(){const{data,error}=await db.from("ads").select("*").eq("active",true);if(error||!data?.length)return;const now=Date.now(),valid=data.filter(a=>(!a.start_at||new Date(a.start_at).getTime()<=now)&&(!a.end_at||new Date(a.end_at).getTime()>=now));const fixed=valid.find(a=>a.type==="fixed"),popup=valid.find(a=>a.type==="popup");if(fixed){const el=document.getElementById("fixedAd");el.innerHTML=adHtml(fixed);el.hidden=false}if(popup){const delay=Math.max(1,Number(popup.popup_delay_seconds)||12)*1000;setTimeout(()=>{const el=document.getElementById("popupAd");document.getElementById("popupAdContent").innerHTML=adHtml(popup);el.hidden=false},delay)}}
document.getElementById("closeAd")?.addEventListener("click",()=>document.getElementById("popupAd").hidden=true);recordHomeView();loadBooks();loadAds();
