-- اصلاح بازدیدها و حذف دسته‌بندی عاشقانه
-- این فایل را فقط یک بار در Supabase > SQL Editor اجرا کنید.

-- اگر جدول بازدیدها از قبل ساخته شده، این بخش خطری ندارد.
create table if not exists public.page_views (
 id bigint generated by default as identity primary key,
 book_id uuid references public.books(id) on delete cascade,
 page text not null,
 created_at timestamptz not null default now()
);

alter table public.page_views enable row level security;
drop policy if exists "Anyone can add page views" on public.page_views;
create policy "Anyone can add page views" on public.page_views
for insert to anon, authenticated with check (true);

drop policy if exists "Admins can read page views" on public.page_views;
create policy "Admins can read page views" on public.page_views
for select to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

-- حذف دسته‌بندی عاشقانه از کتاب‌های فعلی؛ خود کتاب‌ها حذف نمی‌شوند.
update public.books set category = null where trim(coalesce(category,'')) = 'عاشقانه';

-- بررسی نتیجه
select page, count(*) as count from public.page_views group by page order by page;
select count(*) as total_views from public.page_views;
