-- SQL امن و کامل برای سایت کتابخانه
-- این فایل فقط SQL است؛ JavaScript را در SQL Editor قرار ندهید.

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  book_id uuid references public.books(id) on delete cascade,
  page text not null,
  created_at timestamptz not null default now()
);

alter table public.page_views enable row level security;

drop policy if exists "Anyone can add page views" on public.page_views;
create policy "Anyone can add page views"
on public.page_views for insert
to anon, authenticated
with check (true);

drop policy if exists "Admins can read page views" on public.page_views;
create policy "Admins can read page views"
on public.page_views for select
to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

-- کتاب‌ها
alter table public.books enable row level security;

drop policy if exists "Public can read books" on public.books;
create policy "Public can read books"
on public.books for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert books" on public.books;
create policy "Admin can insert books"
on public.books for insert
to authenticated
with check (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

drop policy if exists "Admin can update books" on public.books;
create policy "Admin can update books"
on public.books for update
to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid)
with check (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

drop policy if exists "Admin can delete books" on public.books;
create policy "Admin can delete books"
on public.books for delete
to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

-- اطمینان از وجود و تنظیم Bucketها
insert into storage.buckets (id, name, public, file_size_limit)
values ('books', 'books', true, 104857600)
on conflict (id) do update
set public = true, file_size_limit = 104857600;

insert into storage.buckets (id, name, public, file_size_limit)
values ('covers', 'covers', true, 10485760)
on conflict (id) do update
set public = true, file_size_limit = 10485760;

-- خواندن عمومی فایل‌ها
drop policy if exists "Public read books files" on storage.objects;
create policy "Public read books files"
on storage.objects for select
to public
using (bucket_id = 'books');

drop policy if exists "Public read covers files" on storage.objects;
create policy "Public read covers files"
on storage.objects for select
to public
using (bucket_id = 'covers');

-- آپلود فقط برای مدیر
drop policy if exists "Admin upload books" on storage.objects;
drop policy if exists "Admin upload book files" on storage.objects;
create policy "Admin upload books"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'books'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
);

drop policy if exists "Admin upload covers" on storage.objects;
drop policy if exists "Admin upload cover files" on storage.objects;
create policy "Admin upload covers"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'covers'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
);

-- ویرایش/جایگزینی
drop policy if exists "Admin update books" on storage.objects;
drop policy if exists "Admin update book files" on storage.objects;
create policy "Admin update books"
on storage.objects for update
to authenticated
using (
  bucket_id = 'books'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
)
with check (
  bucket_id = 'books'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
);

drop policy if exists "Admin update covers" on storage.objects;
drop policy if exists "Admin update cover files" on storage.objects;
create policy "Admin update covers"
on storage.objects for update
to authenticated
using (
  bucket_id = 'covers'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
)
with check (
  bucket_id = 'covers'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
);

-- حذف
drop policy if exists "Admin delete books" on storage.objects;
drop policy if exists "Admin delete book files" on storage.objects;
create policy "Admin delete books"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'books'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
);

drop policy if exists "Admin delete covers" on storage.objects;
drop policy if exists "Admin delete cover files" on storage.objects;
create policy "Admin delete covers"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'covers'
  and auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid
);

-- حذف دسته عاشقانه از داده‌های فعلی
update public.books
set category = null
where trim(coalesce(category, '')) = 'عاشقانه';

-- تبلیغات
create table if not exists public.ads (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text,
  image_url text,
  link_url text,
  active boolean not null default true,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.ads enable row level security;

drop policy if exists "Public can read ads" on public.ads;
create policy "Public can read ads"
on public.ads for select
to anon, authenticated
using (active = true and (start_at is null or start_at <= now()) and (end_at is null or end_at >= now()));

drop policy if exists "Admin can read all ads" on public.ads;
create policy "Admin can read all ads"
on public.ads for select
to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

drop policy if exists "Admin can insert ads" on public.ads;
create policy "Admin can insert ads"
on public.ads for insert
to authenticated
with check (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

drop policy if exists "Admin can update ads" on public.ads;
create policy "Admin can update ads"
on public.ads for update
to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid)
with check (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);

drop policy if exists "Admin can delete ads" on public.ads;
create policy "Admin can delete ads"
on public.ads for delete
to authenticated
using (auth.uid() = '71ed2c13-04cc-41a3-8042-7b7a1791000a'::uuid);
