create table if not exists public.page_views (
 id bigint generated by default as identity primary key,
 book_id uuid references public.books(id) on delete cascade,
 page text not null,
 created_at timestamptz not null default now()
);
alter table public.page_views enable row level security;
drop policy if exists "Anyone can add page views" on public.page_views;
create policy "Anyone can add page views" on public.page_views for insert to anon, authenticated with check (true);
drop policy if exists "Admins can read page views" on public.page_views;
create policy "Admins can read page views" on public.page_views for select to authenticated using (auth.uid() = 'YOUR_ADMIN_UUID'::uuid);
